FROM alpine:latest

MAINTAINER fengzhao

# 国内加速
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk update && add --no-cache  openvpn

# 拷贝openvpn.conf配置文件到容器中
COPY openvpn.conf /etc/openvpn/

# 
WORKDIR /etc/openvn

EXPOSE 1194

CMD ["openvpn", "--script-security", "2", "--config", "/etc/openvpn/openvpn.conf"]
